version: "3"

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=${pg_db}
      - POSTGRES_USER=${pg_user}
      - POSTGRES_PASSWORD=${pg_pass}
    ports:
      - "${pg_port}:${pg_port}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - parser

  admin:
    build:
      context: ./admin
    env_file:
      - ./.env
    volumes:
      - static_volume:/app/static/
    depends_on:
      db:
        condition: service_healthy
    networks:
      - parser

  parser:
    build:
      context: ./parsers
    env_file:
      - ./.env
    depends_on:
      - admin
    networks:
      - parser

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
      - static_volume:/static/:ro
    depends_on:
      - admin
    ports:
      - "80:80"
      - "8000:8000"
    networks:
      - parser

networks:
  parser:

volumes:
  static_volume: